# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
stages:
  - deploy_spring_backend
  - deploy_express_app_api
  - deploy_admin_client
  - deploy_vite_client

default:
  image: node:18.15

cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository

variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

deploy_spring_backend:
  stage: deploy_spring_backend
  image: maven:3.8.3-openjdk-17
  before_script:
    - . ci/setup-mvn-proxy.sh && chmod 400 $CI_SSH_KEY
  only:
    - main

  script:
    - cd users && mvn clean package && scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY target/users.war forgeci@51.38.178.218:/opt/tomcat/webapps/users.war

deploy_express_app_api:
  stage: deploy_express_app_api
  before_script:
    - chmod 400 $CI_SSH_KEY && chmod +x api/deploy_production.sh
  only:
    - main

  script:
    - cd api/ && ./deploy_production.sh

deploy_admin_client:
  stage: deploy_admin_client
  before_script:
    - chmod 400 $CI_SSH_KEY && chmod +x admin/deploy_admin_client.sh
  only:
    - main

  script:
    - cd admin && ./deploy_admin_client.sh

deploy_vite_client:
  stage: deploy_vite_client
  before_script:
    - chmod 400 $CI_SSH_KEY && chmod +x client/deploy_vite_client.sh
  only:
    - main

  script:
    - cd client && ./deploy_vite_client.sh
